app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('estate_objects/', include('estate_objects.urls')),
]

estate_objects/urls.py
from django.urls import path
from estate_objects.views import *

urlpatterns = [
    path('', ObjectsList.as_view(), name='objects_list'),
    path('search/', ObjectSearch.as_view(), name='search'),
    path('<int:pk>', ObjectDetails.as_view(), name='object_details'),
    path('add/', ObjectCreate.as_view(), name='object_create'),
    path('<int:pk>/edit/', ObjectUpdate.as_view(), name='object_update'),
    path('<int:pk>/delete/', ObjectDelete.as_view(), name='object_delete'),
    path('solutions/<int:pk>/edit/', SolutionUpdate.as_view(), name='solution_update')

]

estate_objects/models.py
from django.db import models
from django.core.validators import MinValueValidator
from django.urls import reverse

from estate_objects.config import *


class EstateObject(models.Model):
    division = models.CharField(max_length=2, choices=DIVISIONS, verbose_name='Округ')
    district = models.CharField(max_length=32, choices=DISTRICTS, verbose_name='Район')
    address = models.CharField(max_length=256, verbose_name='Адрес')
    obj_type = models.CharField(max_length=16, choices=OBJ_TYPES, verbose_name='Тип объекта')
    condition = models.CharField(max_length=32, choices=CONDITIONS, verbose_name='Состояние объекта')
    area = models.FloatField(validators=[MinValueValidator(0)], verbose_name='Площадь объекта')
    owner = models.CharField(max_length=256, verbose_name='Собственник')
    current_holder = models.CharField(max_length=256, verbose_name='Фактический пользователь')
    media_files = models.FileField(upload_to='photo_video/', verbose_name='Фото/видео')

    def __str__(self):
        return f'Объект №{self.pk}'

    def get_absolute_url(self):
        return reverse('object_details', kwargs={'pk': self.pk})


class AdditionalFieldsList(models.Model):
    field_name = models.CharField(max_length=64, verbose_name='Название поля')
    field_type = models.CharField(max_length=1, choices=FIELD_TYPES, verbose_name='Тип поля')


class AdditionalFields(models.Model):
    obj_id = models.ForeignKey(EstateObject, on_delete=models.CASCADE)
    field_id = models.ForeignKey(AdditionalFieldsList, on_delete=models.CASCADE)
    int_value = models.IntegerField(null=True)
    str_value = models.CharField(max_length=256, null=True)
    date_value = models.DateTimeField(null=True)
    binary_value = models.FileField(upload_to='additional_files/', null=True)
    

class Solution(models.Model):
    obj_id = models.ForeignKey(EstateObject, on_delete=models.CASCADE, verbose_name='ID объекта')
    description = models.TextField(null=True, verbose_name='Формулировка')
    complete_before = models.DateTimeField(null=True, verbose_name='Срок исполнения')
    responsible = models.CharField(max_length=128, null=True, verbose_name='Ответственный')
    discussion_date = models.DateTimeField(null=True, verbose_name='Дата проведения заседания')
    comment = models.TextField(verbose_name='Комментарий')
    

estate_objects/forms.py
from django.forms import ModelForm, IntegerField, NumberInput, DateTimeField, DateInput


from .models import EstateObject, Solution


class AddObjectForm(ModelForm):
    area = IntegerField(
        label='Площадь',
        widget=NumberInput(attrs={"class":"myfield"})
        )
    class Meta:
        model = EstateObject
        exclude = ['media_files']
        # fields = '__all__'


class SolutionForm(ModelForm):
    complete_before = DateTimeField(label='Срок исполнения', widget=DateInput(attrs={'type': 'date'}))
    discussion_date = DateTimeField(label='Дата проведения заседания', widget=DateInput(attrs={'type': 'date'}))

    class Meta:
        model = Solution
        exclude = ['obj_id']
        fields = '__all__'

estate_objects/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from app import settings
from .models import EstateObject, Solution, AdditionalFields
from .forms import AddObjectForm, SolutionForm
from .filters import ObjectFilter


# Create your views here.
class ObjectsList(ListView):
    model = EstateObject
    template_name = 'objects.html'
    context_object_name = 'objects'
    paginate_by = 5


class ObjectDetails(DetailView):
    model = EstateObject
    template_name = 'object.html'
    context_object_name = 'object'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["solution"] = Solution.objects.filter(pk=self.kwargs.get('pk')).first()
        context["additional_fields"] = AdditionalFields.objects.filter(obj_id=self.kwargs.get('pk'))
        return context


class ObjectCreate(CreateView):
    template_name = 'object_create.html'
    form_class = AddObjectForm


class ObjectUpdate(UpdateView):
    template_name = 'object_create.html'
    form_class = AddObjectForm

    def get_object(self, **kwargs):
        obj_id = self.kwargs.get('pk')
        return get_object_or_404(EstateObject, pk=obj_id)


class ObjectDelete(DeleteView):
    template_name = 'object_delete.html'
    queryset = EstateObject.objects.all()
    success_url = reverse_lazy('objects_list')


class ObjectSearch(ListView):
    model = EstateObject
    template_name = 'object_search.html'
    context_object_name = 'objects'
    ordering = ['-pk']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = ObjectFilter(self.request.GET, queryset=self.get_queryset())
        return context


class SolutionUpdate(UpdateView):
    template_name = 'solution_create.html'
    form_class = SolutionForm

    def get_object(self, **kwargs):
        obj_id = self.kwargs.get('pk')
        return get_object_or_404(Solution, pk=obj_id)

    def get_success_url(self, **kwargs):
        obj_id = self.kwargs.get('pk')
        url = f'{settings.SITE_URL}/estate_objects/{obj_id}'
        return url

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="RandomDessert" />
    <title>{% block title %} {% endblock title %}</title>
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <!-- Core theme CSS (includes Bootstrap)-->
    <!-- <link href="{% static 'css/styles.css' %}" rel="stylesheet" /> -->
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-primary bg-primary">
        <div class="container">
            <a class="navbar-brand" href="{% url 'objects_list' %}">Реестр объектов</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'objects_list' %}">Реестр объектов</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'search' %}">Поиск объекта</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'object_create' %}">Новый объект</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <!-- Page content-->
    <div class="container mt-3">
            {% block content %}
            {% endblock content %}
    </div>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <!-- <script src="{% static 'js/scripts.js' %}"></script> -->
</body>

</html>

templates/object.html
{% extends 'base.html' %}

{% block title %}
Информация об объекте {{ object.pk }}
{% endblock title %}

{% block content %}

<h2>Карточка объекта №{{ object.pk }}</h2>

<a class="btn btn-primary" href="{% url 'object_update' object.id %}">Редактировать</a>
<a class="btn btn-primary" href="{% url 'object_delete' object.id %}">Удалить</a>

<h3>Основная информация</h3>
<div class="row mt-3">
    <div class="col-4 border  border-primary">
        <img src="{{ object.media_files }}" alt="">
    </div>
    <div class="col-8">
        <p><b>Округ:</b> {{ object.get_division_display }}</p>
        <p><b>Район:</b> {{ object.get_district_display }}</p>
        <p><b>Адрес:</b> {{ object.address }}</p>
        <p><b>Тип объекта:</b> {{ object.get_obj_type_display }}</p>
        <p><b>Состояние объекта:</b> {{ object.get_condition_display }}</p>
        <p><b>Площадь объекта:</b> {{ object.area }}</p>
        <p><b>Собственник:</b> {{ object.owner }}</p>
        <p><b>Фактический пользователь:</b> {{ object.current_holder }}</p>
        <p><b>Фото/видео:</b> {{ object.media_files }}</p>
    </div>
</div>

<hr>

<h3>Дополнительная информация</h3>
<a class="btn btn-primary" href="{% url 'object_update' object.id %}">Редактировать</a>
<a class="btn btn-primary" href="{% url 'object_update' object.id %}">Добавить поле</a>

{% for add_field in additional_fields %}
<p><b>{{ add_field.field_id.field_name }}:</b> {{ add_field.str_value }}</p>
{% endfor %}

<hr>

<h3>Решение по объекту</h3>
<a class="btn btn-primary" href="{% url 'solution_update' object.id %}">Редактировать</a>
<button class="btn btn-primary">Скачать протокол</button>

<p><b>Формулировка:</b> {{ solution.description }}</p>
<p><b>Срок исполнения:</b> {{ solution.complete_before }}</p>
<p><b>Ответственный:</b> {{ solution.responsible }}</p>
<p><b>Дата проведения заседания:</b> {{ solution.discussion_date }}</p>
<p><b>Комментарий:</b> {{ solution.comment }}</p>

<hr>

<!-- <div class="">
    <a class="nav-link" href="{% url 'objects_list' %}">все объекты</a>

</div> -->




<!-- <div class="modal fade" id="delModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Внимание</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Закрыть"></button>
            </div>
            <div class="modal-body">
                Вы действительно хотите удалить этот объект?
            </div>
            <div class="modal-footer">
                <form method="POST">
                    {% csrf_token %}
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
                    <input class="btn btn-danger" type="submit" value="Удалить">
                </form>
            </div>
        </div>
    </div>
</div> -->


{% endblock %}

templates/object_create.html
{% extends 'base.html' %}

{% block title %}
Создание/изменение объекта
{% endblock title %}

{% block content %}
    <h1>Создание/изменение объекта</h1>
    <form class="d-flex flex-column align-items-start" method="POST">
        {% csrf_token %}
        {{ form }}
        <input class="btn btn-primary mt-3" type="submit" value="Готово">
    </form>
{% endblock content %}

templates/object_delete.html
{% extends 'base.html' %}

{% block title %}
Поиск объектов
{% endblock title %}


{% block content %}

<h2>Вы действительно хотите удалить эту карточку объекта?</h2>
<div class="row mt-3 mb-3">
    <div class="col-4 border  border-primary">
        <img src="{{ object.media_files }}" alt="">
    </div>
    <div class="col-8">
        <p><b>Округ:</b> {{ object.get_division_display }}</p>
        <p><b>Район:</b> {{ object.get_district_display }}</p>
        <p><b>Адрес:</b> {{ object.address }}</p>
        <p><b>Тип объекта:</b> {{ object.get_obj_type_display }}</p>
        <p><b>Состояние объекта:</b> {{ object.get_condition_display }}</p>
        <p><b>Площадь объекта:</b> {{ object.area }}</p>
        <p><b>Собственник:</b> {{ object.owner }}</p>
        <p><b>Фактический пользователь:</b> {{ object.current_holder }}</p>
        <p><b>Фото/видео:</b> {{ object.media_files }}</p>
    </div>
</div>

<form method="POST">
    {% csrf_token %}
    <input class="btn btn-danger" type="submit" value="Удалить">
    <a class="btn btn-secondary" href="{% url 'object_details' object.id %}">Оставить</a>
</form>

{% endblock content %}

templates/object_search.html
{% extends 'base.html' %}

{% block title %}
Поиск объектов
{% endblock title %}


{% block content %}
    <h1>Поиск объектов</h1>
    <h6>заполните одно или несколько полей для поиска</h6>
    <form method='GET'>
        {{ filter.form }}
        <!-- {% for field in filter.form %}
        <div class="row">
            {{field.label_tag}}
            <div>{{field}}</div>
            {% if field.errors%}
            <div class="error">{{field.errors}}</div>
            {% endif %}
        </div>
        {% endfor %} -->
        <input class="btn btn-primary" type='submit' value='Найти'>
    </form>

    <table class="table table-sm table-striped table-hover ">
    
        <thead>
            <th>ID объекта</th>
            <th>Округ</th>
            <th>Район</th>
            <th>Адрес</th>
            <th>Тип объекта</th>
            <th>Состояние объекта</th>
            <th>Площадь объекта</th>
            <th>Собственник</th>
            <th>Фактический пользователь</th>
            <th>Фото/видео</th>
        </thead>
    
        {% for obj in filter.qs %}
        <tr>
            <td><a href="{{ obj.get_absolute_url }}">{{ obj.pk }}</a></td>
            <td>{{ obj.get_division_display }}</td>
            <td>{{ obj.get_district_display }}</td>
            <td>{{ obj.address }}</td>
            <td>{{ obj.get_obj_type_display }}</td>
            <td>{{ obj.get_condition_display }}</td>
            <td>{{ obj.area }}</td>
            <td>{{ obj.owner }}</td>
            <td>{{ obj.current_holder }}</td>
            <td>{{ obj.media_files }}</td>
        </tr>
        {% endfor %}
    </table>
    <!-- <a class="nav-link" href="{% url 'objects_list' %}">все объекты</a> -->


{% endblock content %}

templates/objects.html
{% extends 'base.html' %}

{% block title %}
Список объектов
{% endblock title %}

{% block content %}
<h2>Список объектов</h2>
<!-- <h3>(всего объектов: {{ objects|length }})</h3> -->
<table class="table table-sm table-striped table-hover ">
    <thead>
        <tr>
            <th>ID объекта</th>
            <th>Округ</th>
            <th>Район</th>
            <th>Адрес</th>
            <th>Тип объекта</th>
            <th>Состояние объекта</th>
            <th>Площадь объекта</th>
            <th>Собственник</th>
            <th>Фактический пользователь</th>
            <th>Фото/видео</th>
        </tr>
    </thead>
    <tbody>
        {% for obj in objects %}
        <tr>
            <td><a href="{% url 'object_details' obj.id %}"> {{ obj.pk }} </a></td>
            <td>{{ obj.get_division_display }}</td>
            <td>{{ obj.get_district_display }}</td>
            <td>{{ obj.address }}</td>
            <td>{{ obj.get_obj_type_display }}</td>
            <td>{{ obj.get_condition_display }}</td>
            <td>{{ obj.area }}</td>
            <td>{{ obj.owner }}</td>
            <td>{{ obj.current_holder }}</td>
            <td>{{ obj.media_files }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>



{% if is_paginated %}
<div class="row">
    <div class="col-12 text-center">

        {% if page_obj.has_previous %}
        <a href="?page=1">В начало</a>
        <a href="?page={{ page_obj.previous_page_number }}">&#10094;</a>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
        <a>{{ num }}</a>
        {% elif num > page_obj.number|add:'-2' and num < page_obj.number|add:'2' %} <a href="?page={{ num }}">{{ num }}</a>
            {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">&#10095;</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">В конец</a>
            {% endif %}
            {% endif %}
    </div>

</div>




<!-- <a class="nav-link" href="{% url 'object_create' %}">Новая карточка объекта</a>
    <a class="nav-link" href="{% url 'search' %}">Поиск объектов</a> -->
{% endblock content %}

templates/solution_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

        <style>
            .myfield {
                border: 3px solid #8d1a1a;
                border-radius: 5px;
                height: 25px;
                width: 200px;
                margin: 10px 10px 10px 0;
            }
        </style>

</head>
<body>
    <h1>Корректировка решения по объекту №{{ solution.id }}</h1>
    <form method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Сохранить">
    </form>
</body>
</html>